name: New release deploys to dev

on: ['deployment']

jobs:
  deployment:
    runs-on: ubuntu-18.04

    steps:
    - name: 'Deployment pending'
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'pending'
        token: '${{ github.token }}'

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Push MoH Niger H-EBS to staging
      uses: 'medic/cht-core/.github/actions/deploy-with-medic-conf@master'
      if: github.event.deployment.environment == 'staging'
      with:
        directory: '.'
        hostname: moh-niger-hebs.dev.medicmobile.org
        username: ${{ secrets.STAGING_USERNAME }}
        password: ${{ secrets.STAGING_PASSWORD }}

    - name: Push MoH Niger H-EBS to production
      uses: 'medic/cht-core/.github/actions/deploy-with-medic-conf@master'
      if: github.event.deployment.environment == 'production'
      with:
        directory: '.'
        hostname: moh-niger-hebs.app.medicmobile.org
        username: ${{ secrets.PRODUCTION_USERNAME }}
        password: ${{ secrets.PRODUCTION_PASSWORD }}

    - name: 'Deployment success'
      if: success()
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'success'
        token: '${{ github.token }}'

    - name: 'Slack notify success'
      if: success() && github.event.deployment.environment == 'production'
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: moh-niger-hebs
        SLACK_USERNAME: deliverybot
        SLACK_ICON_EMOJI: ':rocket:'
        SLACK_TITLE: 'Production deployment successful :successful:'
        SLACK_FOOTER: ''
        SLACK_MESSAGE: '<https://github.com/medic/config-cmmb-ke/deployments/activity_log?environment=production|View all deployments>'
        MSG_MINIMAL: commit

    - name: 'Slack notify failure'
      if: failure() && github.event.deployment.environment == 'production'
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: app-services-deployments
        SLACK_USERNAME: deliverybot
        SLACK_COLOR: '#B33A3A'
        SLACK_ICON_EMOJI: ':rocket:'
        SLACK_TITLE: 'Deployment failed :warning:'
        SLACK_FOOTER: '<https://github.com/medic/config-cmmb-ke/deployments/activity_log?environment=production|View all deployments>'
        SLACK_MESSAGE: ${{ github.repository }}
        MSG_MINIMAL: commit

    - name: 'Deployment failure'
      if: failure()
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'failure'
        token: '${{ github.token }}'
